### ISSUE TITLE
请问如何配置多个按键

### ISSUE THREAD

**Issue by gsgqgyq** [BlindingDark/rime-lua-select-character#4]
我想添加多个按键用以选择，可是部署失败。请问支持设置多个按键吗？怎样正确配置呢？
```yaml
key_binder:
  select_first_character: "grave", "9"
  select_last_character: "backslash", "0"
```
